# Generated by Django 5.2.8 on 2025-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('youtube', 'YouTube'), ('instagram', 'Instagram')], default='github', max_length=50)),
                ('handle', models.CharField(max_length=150, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_followers', models.IntegerField(blank=True, null=True)),
                ('last_public_repos', models.IntegerField(blank=True, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
